### ISSUE TITLE
Bot Occasionally Double/Triple Posts Same Post

### ISSUE THREAD

**Issue by HerbalRemedies** [Zsunamy/HLTVDiscordBridge#45]
Dear developer,

Thank you for creating the bot. I'm running a small discord server to try to develop amateur talent in North America. I use your bot in a dedicated ~pro-matches~ channel for members to have easy access to everything involved in the professional scene.

I'm having an issue where the bot sometimes double posts the same content, typically ~20-30 minutes apart. If there is some setting I am missing please let me know. Again, thank you for your time and work.

**Comment by Drachenfalke12** [comment]
I think you are referring to something like this?
![grafik](https://user-images.githubusercontent.com/27867779/112702247-1fd01780-8e93-11eb-82f2-ab68e4c4540b.png)
It's kind of a known problem because some words in the description of the news change and the bot detect it as new News. I'm on a workaround for that already and it should be fixed in the next few days. I'll close this issue when this error then. Thanks for your feedback.

**Comment by Revilum** [comment]
closely related to #34

**Comment by HerbalRemedies** [comment]
Devs,

I did not realize this issue was already captured until I submitted it. I apologize, it's my first time using GitHub. Great to see you guys are already on top of it. 

If you guys are looking for any volunteers, I'm a solid developer. Shoot me a DM if interested: midn1ght#9967

**Comment by Revilum** [comment]
sure! Right now we are quite busy but if you want you can works on some issues.

**Comment by HerbalRemedies** [comment]
Ok, just add me on discord and throw me some stuff to work on.
